import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { formatCurrency, formatDate } from '../../utils/format';
import { Card } from '../../ui/Card';
import { Button } from '../../ui/Button/Button';
const BillPaymentHistoryCard = ({ payments, currency, onRecordPayment, showEmptyState = true, }) => {
    const sortedPayments = [...payments].sort((a, b) => new Date(b.payment_date).getTime() - new Date(a.payment_date).getTime());
    const formatPaymentMethod = (method) => {
        return method.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
    };
    return (_jsxs(Card, { className: "shadow-elevation-2 border border-outline/40", children: [_jsxs("div", { className: "px-6 py-4 border-b border-outline-variant/60 flex justify-between items-center", children: [_jsx("h3", { className: "text-headline-small font-medium text-on-surface", children: "Payment History" }), _jsx(Button, { onClick: onRecordPayment, size: "sm", children: "Record Payment" })] }), _jsx("div", { className: "p-6", children: payments.length === 0 ? (showEmptyState ? (_jsxs("div", { className: "py-8 flex flex-col items-center justify-center text-center border-2 border-dashed border-outline/40 rounded-lg bg-surface-container", children: [_jsx("svg", { xmlns: "http://www.w3.org/2000/svg", className: "h-12 w-12 text-on-surface-variant/40 mb-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 1.5, d: "M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2z" }) }), _jsx("p", { className: "text-body-medium text-on-surface-variant mb-4", children: "No payment records found" }), _jsx(Button, { onClick: onRecordPayment, size: "sm", children: "Record Your First Payment" })] })) : (_jsx("div", { className: "p-6 text-center text-body-medium text-on-surface-variant", children: "No payment records available." }))) : (_jsx("div", { className: "divide-y divide-outline/40", children: sortedPayments.map((payment) => (_jsx("div", { className: "py-4 first:pt-0 last:pb-0", children: _jsxs("div", { className: "flex justify-between items-start", children: [_jsxs("div", { className: "space-y-1", children: [_jsx("p", { className: "text-body-large font-medium text-on-surface", children: formatDate(payment.payment_date) }), _jsx("p", { className: "text-body-small text-on-surface-variant", children: formatPaymentMethod(payment.payment_method) }), payment.reference_number && (_jsxs("p", { className: "text-body-small text-on-surface-variant", children: ["Ref: ", payment.reference_number] }))] }), _jsxs("div", { className: "text-right space-y-1", children: [_jsx("p", { className: "text-body-large font-medium text-on-surface", children: formatCurrency(payment.amount, currency) }), payment.notes && (_jsx("p", { className: "text-body-small text-on-surface-variant line-clamp-2 max-w-xs", children: payment.notes }))] })] }) }, payment.id))) })) })] }));
};
export default BillPaymentHistoryCard;
