#!/usr/bin/env bash
# Migrate existing open issues onto the new label/project state.
# Non-destructive: never closes, never edits issue bodies.
#
# Manual mappings live below in MIGRATION_PLAN. To migrate a new issue,
# add a row. Re-running with the same row is a no-op (gh issue edit
# --add-label is idempotent).
#
# Output: writes/overwrites docs/agents/MIGRATION_REPORT.md with one
# row per migrated issue.

# Each row: issue_number | comma-separated labels to add | effort guess (XS/S/M/L/XL or "")
read -r -d '' MIGRATION_PLAN <<'EOF' || true
23|type:feature,module:investments,priority:p2,status:needs-triage|L
EOF

REPORT_PATH="docs/agents/MIGRATION_REPORT.md"

write_report_header() {
  if [[ "${DRY_RUN:-0}" == "1" ]]; then
    return 0
  fi
  mkdir -p "$(dirname "$REPORT_PATH")"
  {
    echo "# Migration report"
    echo
    echo "Generated by \`scripts/github/bootstrap.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo
    echo "| Issue | Title | Labels applied | Effort | Notes |"
    echo "| --- | --- | --- | --- | --- |"
  } >"$REPORT_PATH"
}

append_report_row() {
  local num="$1"
  local title="$2"
  local labels="$3"
  local effort="$4"
  local notes="${5:-}"
  if [[ "${DRY_RUN:-0}" == "1" ]]; then
    return 0
  fi
  printf '| #%s | %s | %s | %s | %s |\n' "$num" "$title" "$labels" "$effort" "$notes" >>"$REPORT_PATH"
}

set_effort_on_project_item() {
  local issue_number="$1"
  local effort="$2"

  if [[ -z "${PROJECT_NUMBER:-}" || "$PROJECT_NUMBER" == "DRY_RUN" || -z "$effort" ]]; then
    return 0
  fi

  local issue_url="https://github.com/$REPO_FULL/issues/$issue_number"
  local item_id
  item_id="$(run_with_token GH_PROJECT_TOKEN gh project item-add "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --url "$issue_url" --format json 2>/dev/null | jq -r '.id // empty')"
  if [[ -z "$item_id" ]]; then
    warn "Could not add issue #$issue_number to project (may already be present)."
    return 0
  fi

  local project_id effort_field_id effort_option_id
  project_id="$(run_with_token GH_PROJECT_TOKEN gh project view "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --format json | jq -r '.id')"
  local fields_json
  fields_json="$(run_with_token GH_PROJECT_TOKEN gh project field-list "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --format json --limit 100)"
  effort_field_id="$(printf '%s' "$fields_json" | jq -r '.fields[]? | select(.name=="Effort") | .id')"
  effort_option_id="$(printf '%s' "$fields_json" | jq -r --arg e "$effort" '.fields[]? | select(.name=="Effort") | .options[]? | select(.name==$e) | .id')"

  if [[ -z "$effort_field_id" || -z "$effort_option_id" ]]; then
    warn "Could not resolve Effort field/option for issue #$issue_number"
    return 0
  fi

  run_with_token GH_PROJECT_TOKEN gh project item-edit \
    --project-id "$project_id" \
    --id "$item_id" \
    --field-id "$effort_field_id" \
    --single-select-option-id "$effort_option_id" >/dev/null
}

migrate_existing_issues() {
  write_report_header

  while IFS='|' read -r number labels effort; do
    [[ -z "${number:-}" ]] && continue
    log "Migrating issue #$number — labels: $labels, effort: ${effort:-<none>}"

    local title
    title="$(gh issue view "$number" --repo "$REPO_FULL" --json title --jq '.title' 2>/dev/null || echo '(unknown)')"

    run gh issue edit "$number" --repo "$REPO_FULL" --add-label "$labels"

    if [[ -n "$effort" && -n "${PROJECT_NUMBER:-}" ]]; then
      set_effort_on_project_item "$number" "$effort"
    fi

    append_report_row "$number" "$title" "$labels" "${effort:-—}"
  done <<<"$MIGRATION_PLAN"

  log "Migration complete. Report: $REPORT_PATH"
}
